### PR TITLE
Prepare Changelog for 0.13 release

### PR DESCRIPTION
**Pull request by PragTob**
Focussed on the user facing changes, hope I didn't miss any.

Ping @amatsuda as you did a lot of work on master recently :)

Decided to bump the minor, as there's also a feature and it's been some time since the last release :+1:

### CODE REVIEW

**Comment by colszowka** [comment]
Looking great, thanks a lot! @amatsuda please approve if your recent stuff 
is summed up adequately, and let's release!

**Comment by amatsuda** [comment]
I'm fine with my changes. Thank you!

Plus, if time allows, I'd like to see #540 being merged and included in the next release.

**Comment by PragTob** [comment]
That PR looks good to me and it passes the tests. If there are no objections I'm happy to merge it and put it in the Changelog here :)

**Comment by colszowka** [comment]
@PragTob @amatsuda Yes, makes total sense. Merged it!

**Comment by PragTob** [comment]
Rebased against master, and integrated #540 into the changelog.

Looks good? :rocket:

**Comment by emaiax** [comment]
Can't wait to see this running :shipit:

**Comment by colszowka** [comment]
Merged!

**Comment by PragTob** [comment]
:tada: 

@colszowka do you want to do the release or shall I bump the version number and release? I'll most likely have time this evening :)

**Comment by colszowka** [comment]
@PragTob Sure thing, feel free to ship! I held off on that yesterday evening because I was about to jump into bed and didn't want to leave any potential disasters behind :)

**Comment by PragTob** [comment]
Consider it hopefully done without any disasters :D

**Pull request merged**
