### PR TITLE
Check if stored_data is not empty before parsing it to json

### PR DESCRIPTION
**Pull request by JanStevens**
In light of issue #406

### CODE REVIEW

**Comment by bf4** [comment]
Is it possible that the bug is actually that stored_data should be `nil` not `''` or `"null"` and that is a bug originated in how stored_data is generated?  That said, the fix could also be `if stored_data && !stored_data.empty?`

**Comment by JanStevens** [comment]
This largely depends on your JSON implementation, It seems that Oj for example returns nil in case `stored_data` is nil. Standaard JSON lib will raise a `TypeError`

I agree that the fix could also be to check if `stored_data` is not empty (which would make sense)

Regards

**Comment by bf4** [comment]
Would you mind rebasing your commits and adding a test for this?

**Comment by JanStevens** [comment]
Looking at the test suite and current solutions I would say its already being tested:

- https://github.com/colszowka/simplecov/blob/master/spec%2Fmerge_helpers_spec.rb?ts=2#L48-L58

I can add specific test to see that we always return an empty hash incase the file couldn't be read but the `be_empty` seems to be sufficient.

**Comment by JanStevens** [comment]
Lets merge merge merge? xD

**Comment by xaviershay** [comment]
If it was already being tested, then why weren't those tests failing?

**Comment by xaviershay** [comment]
I'm not convinced this addresses the issue. See comments on #406. Closing until someone convinces me otherwise.

**Pull request closed without merging**
