### PR TITLE
Added feature from #104 allowing a array to be passed in a filter

### PR DESCRIPTION
**Pull request by JanStevens**
After two years of waiting we finally can use arrays in simplecov groups

Thanks for the original PR #104 since the author did not respond after 2 years I decided to copy past the PR based on the master branch.

### CODE REVIEW

**Comment by JanStevens** [comment]
I have no clue why Travis is failing, if anyone can help

**Comment by colszowka** [comment]
Thanks! The tests broke because we had an order issue, see #362 and #372

I have three requests for you:
* Please rebase/force push against master so this gets green
* Could you please update the relevant section of the README with examples
* And finally, a cucumber feature for this would be great - I think expanding [this one](https://github.com/colszowka/simplecov/blob/master/features/rspec_groups_and_filters_complex.feature) should suffice.

Thanks!

**Comment by JanStevens** [comment]
Allright, done everything!

I just added a small example to the README, I hope it suffices

**Comment by JanStevens** [comment]
*bump* any update on this when this will be merged/released?

**Comment by bf4** [comment]
@colszowka ok with you?

**Pull request merged**
