### PR TITLE
Bump to cucumber 4

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
I actually expected this to just work but there's some issues, so I'm just opening a draft PR so you can pick it up if you want @PragTob since I don't plan to work on it for now.

### CODE REVIEW

**Comment by PragTob** [comment]
Thanks @deivid-rodriguez :raised_hands: - I had similar hopes, not sure I'll work on it right now as I already spend my time at work fighting with gem updates these days :grin: I might though.

**Comment by PragTob** [comment]
```
activesupport-6.0.3.2 requires ruby version >= 2.5.0, which is incompatible with
the current version, ruby 2.4.10p364
```

Mehhh.

**Comment by PragTob** [comment]
```
expected: 6
     got: 5

(compared using ==)
 (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/html_steps.rb:14:in `block (3 levels) in <top (required)>'
./features/step_definitions/web_steps.rb:5:in `block in with_scope'
./features/step_definitions/web_steps.rb:5:in `with_scope'
./features/step_definitions/html_steps.rb:12:in `block (2 levels) in <top (required)>'
./features/step_definitions/html_steps.rb:11:in `each'
./features/step_definitions/html_steps.rb:11:in `/^I should see the groups:$/'
features/cucumber_basic.feature:18:in `I should see the groups:'

Failing Scenarios:
cucumber features/cucumber_basic.feature:10 # Scenario: 

71 scenarios (1 failed, 4 skipped, 66 passed)
453 steps (1 failed, 30 skipped, 422 passed)
1m13.395s
```

That's oddly strange. But otherwise seemed to run fine, I'll take a look.

**Comment by PragTob** [comment]
@deivid-rodriguez if you agree with my latest commit we have an ok chance of merging this :woman_dancing:

**Comment by deivid-rodriguez** [comment]
Sure!

**Comment by deivid-rodriguez** [comment]
One question, does this stay green for you if you run the bad scenario in isolation, cause I tried this same solution, and couldn't manage to get consistent results :confounded:

**Comment by PragTob** [comment]
@deivid-rodriguez it did, I'll double check this evening though!

**Comment by deivid-rodriguez** [comment]
I don't know what I was doing, but I tried this again now and it's working totally fine :+1:.

**Pull request merged**
