### PR TITLE
Document parallel_tests / command_name combination

### PR DESCRIPTION
**Pull request by srawlins**
When using `SimpleCov.command_name`, you forfeit the parallel_tests support, which only exists when SimpleCov is guessing command names.

This pull request adds some documentation to the command_name section of the README, discussing how to incorporate parallel_tests TEST_ENV_NUMBER into a command_name.

### CODE REVIEW

**Comment by plicjo** [comment]
Hey, just came across this in 2015. Is this still relevant? This has been open for a year!

**Comment by plicjo** [comment]
@sferik

**Comment by sferik** [comment]
Yes, but it can’t be automatically merged. If @srawlins rebases, I will gladly merge the change. Otherwise, I’ll need resolve the merge conflicts myself, which I don’t have time for at the moment.

**Comment by bf4** [comment]
`git checkout master; git fetch origin; git reset --hard origin/master; git checkout add-parallel-command-name-doc; git reset --hard master; git cherry-pick 15f819eb6de753bc32c15c8e1996883eef051864`

**Comment by srawlins** [comment]
Sorry about that. I've rebased. It's ready.

**Comment by bf4** [comment]
@sferik Ok to merge? It looks ok to me but I'm tired and might have code blindness

**Comment by sferik** [comment]
Yeah. Looks good! :+1:

**Pull request merged**
