### PR TITLE
Fixed warnings

### PR DESCRIPTION
**Pull request by fornellas**
Fix for #446

### CODE REVIEW

**Comment by colszowka** [comment]
Thanks for looking into this @fornellas - we do have an existing PR for this fix by now already though with #447, which also uses the same strategy for initializing the var as we have used in the rest of the methods in the module. Only thing it's waiting for is getting #448 ready - sorry for the double work!

**Comment by fornellas** [comment]
No problem, glad to help :-D

**Comment by fornellas** [comment]
BTW, I'd consider enabling warnings in RSpec, to avoid future mistakes.

**Comment by colszowka** [comment]
@fornellas Yes, I thought so too - I think at one point we did have those, but maybe I'm mistaken. Would you mind sending in a PR with this? :heart:

**Pull request closed without merging**
