### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by mhutter**
So we can get 0.10.1 rolling and I can get this annoying warning out of my builds :dancer:

### CODE REVIEW

**Comment by bf4** [comment]
Thank you so much!

**Comment by bf4** [comment]
Can you link to / reference the prs/issus/authors?

**Comment by mhutter** [comment]
Hey! added some links and removed stuff not interesting for "end users"

**Comment by xaviershay** [comment]
I didn't see this and duplicated your work. I'm sorry :(

https://github.com/colszowka/simplecov/pull/425

**Pull request closed without merging**
