### PR TITLE
Avoid forking test for JRuby since fork is not implemented

### PR DESCRIPTION
**Pull request by donv**
This fixes 10 test failures for JRuby in travis

### CODE REVIEW

**Comment by xaviershay** [comment]
seems this changed a magic coverage constants in the others tests :(

LGTM once those are fixed.

**Comment by donv** [comment]
@xaviershay I assume that since I added new lines to the source, and they are covered, the percentage increased.  I'll adjust those, then.

**Comment by donv** [comment]
@xaviershay Simplified the test change to avoid changing the coverage percentage.

This fixes all but one test for JRuby, and that was failing before this PR.  I will look at that separately from this PR.

Good to merge?

**Comment by colszowka** [comment]
LGTM, merging. Thank you!

**Pull request merged**
