### PR TITLE
Disable Bundler the Aruba way

### PR DESCRIPTION
**Pull request by mvz**
I removed the `@wip` tags just to demonstrate that this works with Aruba master. That bit 
should not be merged (hence the draft status).

This method of disabling Bundler is indeed not working with Aruba 0.14.14.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I think it does make sense to remove the `@wip` tags here since this issue is the reason why they are there I believe.

**Comment by deivid-rodriguez** [comment]
Oh, no, I see it's because of a race condition, sorry about that. :pray:

**Comment by PragTob** [comment]
@mvz thanks a lot! :tada: 

Yup that's the race condition they're there for which I might or not might try to dig into at some point in time but it seems daunting :scream: 

So if we could reinstate those, that'd be great. The failing build war JRuby version that is somehow flaky on travis (sometimes doesn't know how to install it...) - restarted that build!

**Comment by mvz** [comment]
Ok, seeing that the specs pass I'll reinstate the `@wip` tags.

**Comment by PragTob** [comment]
Thanks a lot @mvz ! :green_heart: 

IMG_20190130_181749

**Pull request merged**
