### PR TITLE
Fix crashes with uneven number of nocov instructions

### LINKED ISSUE #846: Error: uneven number of nocov comments detected
In versions prior to 0.18 we could add the `# :nocov:` comment at the beginning of files, without providing a closing tag, to ignore the entire file.

In version 0.18 this errors with `uneven number of nocov comments detected` followed by what seems to be an uncaught exception:

```
simplecov-0.18.0/lib/simplecov/source_file.rb:186:in `block in process_skipped_lines': undefined method `-' for nil:NilClass (NoMethodError)
```

Was the ability to ignore the whole file using just a single `# :nocov:` removed, or is this a bug?
I did not spot anything to that effect in the changelog.

### PR DESCRIPTION
**Pull request by PragTob**
Fixes #846
We just assume them to go until the end. Test against a full nocov
for the file as well as a small mixture.

If this passes on CI I'll cut a new bugfix release.

cc: @DannyBen

### CODE REVIEW

**Comment by PragTob** [comment]
And it's failing on JRuby - yeehaawwww!

**Comment by PragTob** [comment]
And now github can't seem to reach the ubuntu packages or the IP is outdated and cached or what not so we can't get Java and run CI vs JRuby :cry: 

```
 Err:1 http://security.ubuntu.com/ubuntu bionic-updates/universe amd64 openjdk-8-jre-headless amd64 8u232-b09-0ubuntu1~18.04.1
  404  Not Found [IP: 52.168.50.79 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/o/openjdk-8/openjdk-8-jre-headless_8u232-b09-0ubuntu1~18.04.1_amd64.deb  404  Not Found [IP: 52.168.50.79 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by deivid-rodriguez** [comment]
I figure we could try running the workflow on https://github.com/docker-library/openjdk, so we don't need to install java everytime.

**Comment by PragTob** [comment]
yeah that seems like a great idea, right now I'm just "F5"ing hoping it comes back :grin:

**Comment by PragTob** [comment]
Still borked :'(

**Comment by PragTob** [comment]
still broken, wow guess I really gotta go to docker land or something

**Comment by PragTob** [comment]
Pulled in master without JDK installation. Should hopefully pass CI now and subsequently be released :dancer:

**Pull request merged**
