### PR TITLE
#16 Uncovered source files.

### PR DESCRIPTION
**Pull request by jwickard**
implements Feature from issue #16

Off by default, but if someone wants it, they can just set show_uncovered_files to true in the config block.

Why aren't there tests?

I tried to write a few features to demonstrate the functionality but the way the test harness run it touches the uncovered source file and shows up in the coverage data.  So basically when I run the tests I can't recreate the issue.

If it's a big deal maybe I can spend some time in the future trying to work that up.

### CODE REVIEW

**Comment by bf4** [comment]
You up for updating this?

**Comment by sferik** [comment]
Ping? I’m trying to put together a new release. Please update if you want this feature included.

**Comment by bf4** [comment]
@jwickard would you be up to rebasing this?

**Comment by xaviershay** [comment]
Replaced by #422.

**Pull request closed without merging**
