### PR TITLE
Make sure the license file gets included with the gem

### PR DESCRIPTION
**Pull request by tas50**
When the list of files to include was pruned down the LICENSE file was
accidently pruned as well. This causes issues for projects that do
strict license validation on depdendencies.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by tas50** [comment]
I didn't update the changelog because I wasn't sure what you'd want it to look like, but we'd love if this went out as 0.16.1.

**Comment by PragTob** [comment]
Sorry that happened!

I think renaming the file to `LICENSE` is more in line with community standards so that'd be my preferred change :)

**Comment by tas50** [comment]
@PragTob Updated to use LICENSE

**Comment by PragTob** [comment]
@tas50 and released as 0.16.1

**Pull request merged**
